// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_welcome_to_the_voyage = "CgkIw-3oxbANEAIQAQ"; // <GPGSID>
        public const string achievement_beat_multistep_world = "CgkIw-3oxbANEAIQAw"; // <GPGSID>
        public const string achievement_beyond_the_voyage = "CgkIw-3oxbANEAIQCA"; // <GPGSID>
        public const string achievement_the_creator = "CgkIw-3oxbANEAIQBg"; // <GPGSID>
        public const string achievement_beat_switch_world = "CgkIw-3oxbANEAIQBA"; // <GPGSID>
        public const string achievement_beat_block_world = "CgkIw-3oxbANEAIQAg"; // <GPGSID>
        public const string achievement_sending_precious_cargo = "CgkIw-3oxbANEAIQBw"; // <GPGSID>
        public const string achievement_beat_rotate_world = "CgkIw-3oxbANEAIQBQ"; // <GPGSID>

}

